### ISSUE TITLE
과제 제출 필수 사항

### ISSUE THREAD

**Issue by fineman999** [fineman999/wanted-pre-onboarding-backend#11]
# 필수 사항

</br>
</br>

## Todo

- [x] 과제의 소스코드는 반드시 본인의 GitHub 레포지토리에 Public으로 설정하여 업로드 해주세요.
- [x] 레파지토리의 이름은 wanted-pre-onboarding-backend로 지정해야 합니다.

### README.md 파일에는 다음과 같은 사항들이 포함되어야 합니다:
- [x] 지원자의 성명
- [x] 애플리케이션의 실행 방법 (엔드포인트 호출 방법 포함)
- [x] 데이터베이스 테이블 구조
- [x] 구현한 API의 동작을 촬영한 데모 영상 링크
- [x] 구현 방법 및 이유에 대한 간략한 설명
- [x] API 명세(request/response 포함)
- [x] 과제 제출은 참가 신청 시 수행한 과제의 레포지토리 주소를 제출하면 됩니다.

</br>
</br>
