### ISSUE TITLE
추가 기능

### ISSUE THREAD

**Issue by fineman999** [fineman999/wanted-pre-onboarding-backend#15]
# Description
요구사항에 맞게 API를 만든 후에 아래의 기능을 추가할 경우 가산점이 주어집니다.

</br>
</br>

## Todo

- [x] 통합 테스트 또는 단위 테스트 코드를 추가한 경우
- [x] docker compose를 이용하여 애플리케이션 환경을 구성한 경우
- [x] (README.md 파일에 docker-compose 실행 방법 반드시 기입)
- [x] 클라우드 환경(AWS, GCP)에 배포 환경을 설계하고 애플리케이션을 배포한 경우
- [x] (README.md 파일에 배포된 API 주소와 설계한 AWS 환경 그림으로 첨부)

</br>
</br>
